import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <h1>Hey Hey and welcome again</h1>
    <br/>
    <p>Ayoub Kassi welcome</p>

    <Link href="/about">
        <a>About</a>
    </Link>
    </div>
  )
}
